### ISSUE TITLE
Code review for team 108(The Mambas)

### ISSUE THREAD

**Issue by ebeagusamuel** [ozovalihasan/escape-rpg-game#1]
- Nice work so far.
- You should try to position the elements of the start scene and some other scenes correctly.
- Do not forget to make the fight zone visible.
- Remember to update the player score as it fights with the dragon.

**Comment by ozovalihasan** [comment]
Thanks, @ebeagusamuel for your feedback. I fixed the positions of the elements. I added visible and hidden areas for battle. I fixed score to be updated at the end of the battle
